### ISSUE TITLE
Do not bundle php-cs-fixer with the coding-standard

### ISSUE THREAD

**Issue by patrickjahns** [owncloud/coding-standard#14]
Bundling `php-cs-fixer` with `owncloud/coding-standard` leads to the problem, that when there are fixes with php-cs-fixer, we would require to version bump `owncloud/coding-standard` for the php-cs-fixer fixes

Ref:  https://github.com/owncloud/files_primary_s3/issues/113#issuecomment-412441902

**Comment by DeepDiver1975** [comment]
so we can basically drop the idea of having one dev-dependency which drags all tools into a repo?

Do we convert this into a phar based approach then? hmmm ..... would require a version bump as well if php-cs-fixer needs an update ....

**Comment by patrickjahns** [comment]
Need to setup some tests in a separate repository/package approach to see if dropping `composer.lock` would lead to the correct behavior.
