### ISSUE TITLE
[Proposal] Use wellknown coding style from other php projects

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/coding-standard#17]
Instead of maintaining a long list of custom selected rules I propose to use one of the most common used coding styles: symfony.

The config to be added to each repo could be as easy as:

```php
<?php

$config = PhpCsFixer\Config::create();
$config->getFinder()
    ->exclude('vendor')
    ->in(__DIR__);
$config->setRules([
    '@PSR1' => true,
    '@Symfony' =>true
]);

return $config; 

```

No need for any custom package ....

**Comment by karakayasemi** [comment]
IMHO, sticking to common standards is beneficial for maintainability. Also, adapting to this is easy for newcomer developers who already used to this standard.

**Comment by phil-davis** [comment]
https://symfony.com/doc/3.4/contributing/code/standards.html seems to have an English description of the standards. I am not sure if PHP CS fixer will enforce everything on that page.

A couple of things that I noticed:

1) https://en.wikipedia.org/wiki/Yoda_conditions - I quite like them, others will have varying opinions.

2) Declare all the arguments on the same line as the method/function name, no matter how many arguments there are - that seems a bit odd when the method name is quite long and it has a long list of parameters.

(1) is fine with me! (2) can be lived with. The rest seems "a good thing" (tm)

**Comment by DeepDiver1975** [comment]
An alternative to Symfony would be PSR2 - https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/03e13fb91c775a151dc57ae51e80ba3f2abe7da6/src/RuleSet.php#L33 - https://www.php-fig.org/psr/psr-2/

**Comment by patrickjahns** [comment]
PSR2 is very lenient - we are already PSR2 compatible. 

Initial proposal was already to move to a more common standard in the php community. These days it seems to be PSR2 and Symfony. 

Down side is, that some of these changes to move to Symfony standard might cause bugs/errors. I'd propose to do this move gradually in apps and for core with the next major release. This would give us enough time to be sure these code style adjustments do not create unforseen bugs

**Comment by DeepDiver1975** [comment]
This will never happen :wave:
